use moody;

insert into user(user_name, password) values ('hyunblee', '{bcrypt}$2a$10$4kWzwruKCB.0KtXOwYIlbe0rThqMI6e0pHFeZszpWnd2cPe1mgH3q');
insert into member_roles(member_id, roles) values (1, 'USER');

insert into user(user_name, password) values ('yujin', '{bcrypt}$2a$10$4kWzwruKCB.0KtXOwYIlbe0rThqMI6e0pHFeZszpWnd2cPe1mgH3q');
insert into member_roles(member_id, roles) values (2, 'USER');
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","01", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","02", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","03", 3, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","04", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","05", 1, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","06", 1, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","07", 1, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","08", 1, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","09", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","10", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","11", 3, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","12", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","13", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","14", 1, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","15", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","16", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","17", 3, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","18", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","19", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","20", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","21", 1, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","22", 3, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","23", 3, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","24", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","25", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","26", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","27", 2, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","28", 1, 2);
insert into heatmap(year, month, day, feeling, user_id) values ("2023","01","29", 2, 2);

insert into quote(saying) values ("타인이 널 어떻게 느끼는지는 너가 관여할 수 없는 것이다.\n그러니 바꾸려하지 말고 오로지 너의 인생을 살고 행복하여라.\n-박신영-");
insert into quote(saying) values ("과거가 얼마나 힘들었든지간에\n넌 언제나 다시 시작할 수 있다.\n-박신영-");
insert into quote(saying) values ("고통이 널 붙잡고 있는게 아니라,\n너가 고통을 붙잡고 있는 것이다.\n-박신영-");
insert into quote(saying) values ("너 자신을 극복할 수 있으면\n현실에서도 승리할 수 있다.\n-박신영-");
insert into quote(saying) values ("사람들에게 너의 계획을 말하지 말고,\n결과물을 보여주어라.\n-박신영-");
insert into quote(saying) values ("변화 그 자체는 결코 고통이 아니지만,\n변화에 저항하는 것은 고통 그 자체이다.\n-박신영-");
insert into quote(saying) values ("영원한건 아무것도 없다.\n너무 스트레스를 받지 마라.\n상황이 얼마나 나쁘건간에 그것은 곧 변할 것이기 때문이다.\n-박신영-");
insert into quote(saying) values ("우리네 삶에서의 모든 상황은 그저 찰나이다.\n상황이 좋지 않아도 점차 나아진다는 것을 기억하면 된다.\n-박신영-");
insert into quote(saying) values ("타인이 너를 무엇으로 생각하는지는 중요치 않다.\n스스로 생각하는 너 자신이 너의 모든 것이다.\n-박신영-");
insert into quote(saying) values ("타인의 삶과 비교하지 마라.\n해와 달은 서로를 비교하는 법이 없다.\n그들은 단지 그들의 시간대에서 빛나고 있는 그 뿐이다.\n-박신영-");
insert into quote(saying) values ("타인에게 영감을 주기 위해\n네 인생을 살지 말고,\n너 자신에게 영감을 주는 인생을 살아라.\n-박신영-");
insert into quote(saying) values ("타인이 널 좋아하도록 자신을 바꾸지 마라.\n오로지 솔직한 너 자신이 된다면\n올바른 사람들은 진짜 너의 모습을 사랑하게 될 것이다.\n-박신영-");

-- insert into member_roles(member_id, roles) values ('user', 'USER');